### ISSUE TITLE
Implement Coverage improvement for Clipper::splitSegments_ and isPointInPolygon

### ISSUE THREAD

**Issue by bjornthiberg** [group19-se24/assignment-3#13]

**Comment by samshahriari** [comment]
Tests that cover branches 20, 21, 25, and 26 are missing.

25 happens when n_2 is 1 and the normalized distance between pt_0  and pt_1 is 0

**Comment by samshahriari** [comment]
For isPointInPolygon it is completely untested.
Tests could be to have polygon without points, a polygon with a point outside and a polygon with a point inside.
