### ISSUE TITLE
Count the cyclomatic complexity of Clipper::clip

### ISSUE THREAD

**Issue by bjornthiberg** [group19-se24/assignment-3#5]

**Comment by torenylen** [comment]
before switch-case E: 22
after switch-case E: 15
E tot: 37

before switch-case N: 12
after switch-case N: 8
N tot: 20

M = 37 - 20 + 2 = 19

**Comment by Samkth123** [comment]
Before CASE:
N = 12
E = 22

After case:
E = 17 
N = 7

M = 39 - 19 +2 = 22
